series: Basic OpenGL with GLFW
title: Intro to Shaders
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use shaders to change the color and position of rendered shapes.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: World Matrices